# Plotting
Load the .eigenvec file & plot the columns you're interested in

pca <- read.delim("/bigdata/koeniglab/jmarz001/CCXXIRAD/results/pca.eigenvec")

pca_MAF_exclude_50LD <- read.delim("/bigdata/koeniglab/jmarz001/CCXXIRAD/results/pca_MAF_exclude_50LD.eigenvec")
pca_MAF_exclude_10LD <- read.delim("/bigdata/koeniglab/jmarz001/CCXXIRAD/results/pca_MAF_exclude_10LD.eigenvec")

# replace KL numbers with generation numbers for plotting
pca$FID <- gsub("24", "F25", pca$FID)
pca$FID <- gsub("267", "F11", pca$FID)

pca_MAF_exclude_50LD$FID <- gsub("24", "F25", pca_MAF_exclude_50LD$FID)
pca_MAF_exclude_50LD$FID <- gsub("267", "F11", pca_MAF_exclude_50LD$FID)

pca_MAF_exclude_10LD$FID <- gsub("24", "F25", pca_MAF_exclude_10LD$FID)
pca_MAF_exclude_10LD$FID <- gsub("267", "F11", pca_MAF_exclude_10LD$FID)

# this is code that generates a beautiful plot <3
ggplot(pca, aes(PC1, PC2)) + geom_point(aes(color = pca$FID)) + xlab("PC1 (8.036%)") + theme_minimal() + ylab("PC2 (7.045%)") + scale_color_manual("Generations", values=wes_palette("GrandBudapest1")) + theme(axis.text=element_text(size=12)), axis.title=element_text(size=14,face="bold")

## comparing LD == 50 vs. 10 as pca plots
ggplot(pca_MAF_exclude_50LD, aes(PC1, PC2)) + geom_point(aes(color=pca_MAF_exclude_50LD$FID)) + theme_minimal() + scale_color_manual("Generations", values=wes_palette("GrandBudapest1")) + theme(axis.text=element_text(size=12), axis.title=element_text(size=14, face="bold"))

ggplot(pca_MAF_exclude_10LD, aes(PC1, PC2)) + geom_point(aes(color=pca_MAF_exclude_10LD$FID)) + theme_minimal() + scale_color_manual("Generations", values=wes_palette("GrandBudapest1")) + theme(axis.text=element_text(size=12), axis.title=element_text(size=14, face="bold"))
# there's no (visual) difference between the two graphs
# also no difference in the eigenvals
# PC1 and PC2 == 12.8531 & 10.5159
#so I should use VIF==10 or lower
# the smaller grouping to the right is made up of about 92 points, which, after filtering, represents about 1/4 of the samples sequenced


# for first "pca" dataset
######################################
# extreme values of PC1 from
# 24_427 w/ PC1=-0.17002700
# 24_348 w/ PC1= 0.08540640

# extreme values of PC2 from
# 24_317 with PC2=-0.27650500
# 267_235 with PC2=0.10439700
