# convert all non-MAF's into true MAF's
F25_MAF[F25_MAF$V1 > 0.5, "V1"] <- 1 - (F25_MAF[F25_MAF$V1 > 0.5, "V1"] )
F11_MAF[F11_MAF$V1 > 0.5, "V1"] <- 1 - (F11_MAF[F11_MAF$V1 > 0.5, "V1"] )
minor_allele_freq[minor_allele_freq$MAF > 0.5, "MAF"] <- 1 - (minor_allele_freq[minor_allele_freq$MAF > 0.5, "MAF"] )
# set up break points for frequency bars
br = seq(0,0.5,by=0.1)
ranges = paste(head(br,-1), br[-1], sep=" - ")

freq25 = hist(F25_MAF$V1, breaks=br, include.lowest=TRUE, plot=FALSE)
freq11 = hist(F11_MAF$V1, breaks=br, include.lowest=TRUE, plot=FALSE)
both_pops = hist(minor_allele_freq$MAF, breaks=br, include.lowest=TRUE, plot=FALSE)

F11_freq_counts = data.frame(range = ranges, frequency = freq11$counts)
F25_freq_counts = data.frame(range = ranges, frequency = freq25$counts)
both_freq_counts = data.frame(range = ranges, frequency = both_pops$counts)

# graph as a histogram
ggplot(minor_allele_freq, aes(MAF.Percent)) + geom_histogram(bins = 200, fill="pink") + theme(axis.text=element_text(size=12), axis.title=element_text(size=14,face="bold")) + xlab("MAF") + theme_classic()

# to follow plotting conventions, do all 3 bars on the same plot in chunks
ggplot(df2, aes(x=range, y=value, fill=variable)) + geom_bar(stat='identity', position='dodge', width=0.7) + theme_classic() + xlab("Minor Allele Frequency Ranges") + ylab("Proportion") + scale_fill_brewer(palette = "YlOrRd")

# the easy way to do the site frequency spectrum plots
barplot(table(cut(F11_MAF[,1],seq(0,.5,.05))))
# not sure how to apply this to make one plot so...


# bins need to be by 5% not 10%
br = seq(0,0.5,by=0.05)
ranges = paste(head(br,-1), br[-1], sep=" - ")

freq25 = hist(F25_MAF$V1, breaks=br, include.lowest=TRUE, plot=FALSE)
freq11 = hist(F11_MAF$V1, breaks=br, include.lowest=TRUE, plot=FALSE)
both_pops = hist(minor_allele_freq$MAF, breaks=br, include.lowest=TRUE, plot=FALSE)

F11_freq_counts = data.frame(range = ranges, frequency = freq11$counts)
F25_freq_counts = data.frame(range = ranges, frequency = freq25$counts)
both_freq_counts = data.frame(range = ranges, frequency = both_pops$counts)

df1 <- data.frame(both_freq_counts$range, both_freq_counts$frequency, F11_freq_counts$frequency, F25_freq_counts$frequency)
colnames(df1) <- c("range", "both", "F11", "F25")
df2 <- melt(df1)

# now plot your 3 frequencies on a ggplot bar graph again, by 5%'s this time
ggplot(df2, aes(x=range, y=value, fill=variable)) + geom_bar(stat='identity', position='dodge', width=0.7) + theme_classic() + xlab("Minor Allele Frequency Ranges") + ylab("Proportion") + scale_fill_brewer(palette = "YlOrRd")


# add a neutral selection allele frequency spectrum function for comparison with your data
# is my population deviating from neutral selection?

# plot a function line over the top of my ggplot graph with stat_function
#stat_function(mapping = NULL, data = NULL, geom = "path", position = "identity", fun, n = 101, args = list(), ...)
# fun: function to use
# n: number of points to interpolate along
# args: list of additional arguments to pass to ‘fun’

# original graph
p <- ggplot(df2, aes(x=range, y=value, fill=variable)) + geom_bar(stat='identity', position='dodge', width=0.7) + theme_classic() + xlab("Minor Allele Frequency Ranges") + ylab("Frequency") + scale_fill_brewer(palette = "YlOrRd")

# neutral selection function: 2Neu/i
# Ne=population size, u = mutation rate, i=sites
# mutation rate (empirically calculated) = 7e-9
# barley nucleotide diversity estimate ~ 0.005 (Morrell 2003)
# effective population size = theta/4u = 0.005/4*7e-09 = 178571.4

# the finally add 1500 to the whole thing to just get the line above the minimum value of the MAFs so you can see where the line fits over the data
funct <- function(x) ((178571.4*2*7e-09)/(x)) + 1500
p + stat_function(fun = funct)

# also drew a y-intercept at 1500 so I could see it's about the lowest point on the graph and what a straight line over the data looks like
p + stat_function(fun = funct) + geom_hline(yintercept=1500)
